from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Setting(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(367, 412)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.apply_wind = QtWidgets.QPushButton(self.centralwidget)
        self.apply_wind.setGeometry(QtCore.QRect(220, 40, 75, 21))
        self.apply_wind.setObjectName("apply_wind")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.width = QtWidgets.QLabel(self.centralwidget)
        self.width.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.width.setObjectName("width")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 80, 391, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 160, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.s_1 = QtWidgets.QSlider(self.centralwidget)
        self.s_1.setGeometry(QtCore.QRect(100, 130, 160, 22))
        self.s_1.setOrientation(QtCore.Qt.Horizontal)
        self.s_1.setObjectName("s_1")
        self.apply_color = QtWidgets.QPushButton(self.centralwidget)
        self.apply_color.setGeometry(QtCore.QRect(280, 160, 75, 23))
        self.apply_color.setObjectName("apply_color")
        self.color_box = QtWidgets.QLabel(self.centralwidget)
        self.color_box.setGeometry(QtCore.QRect(70, 160, 21, 21))
        self.color_box.setObjectName("color_box")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 220, 391, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 261, 16))
        self.label_2.setObjectName("label_2")
        self.b_2 = QtWidgets.QSlider(self.centralwidget)
        self.b_2.setGeometry(QtCore.QRect(10, 310, 160, 22))
        self.b_2.setOrientation(QtCore.Qt.Horizontal)
        self.b_2.setObjectName("b_2")
        self.apply_beck = QtWidgets.QPushButton(self.centralwidget)
        self.apply_beck.setGeometry(QtCore.QRect(210, 310, 75, 23))
        self.apply_beck.setObjectName("apply_beck")
        self.color_back_la = QtWidgets.QLabel(self.centralwidget)
        self.color_back_la.setGeometry(QtCore.QRect(180, 310, 21, 21))
        self.color_back_la.setObjectName("color_back_la")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 201, 16))
        self.label_3.setObjectName("label_3")
        self.s_2 = QtWidgets.QSlider(self.centralwidget)
        self.s_2.setGeometry(QtCore.QRect(100, 160, 160, 22))
        self.s_2.setOrientation(QtCore.Qt.Horizontal)
        self.s_2.setObjectName("s_2")
        self.s_3 = QtWidgets.QSlider(self.centralwidget)
        self.s_3.setGeometry(QtCore.QRect(100, 190, 160, 22))
        self.s_3.setOrientation(QtCore.Qt.Horizontal)
        self.s_3.setObjectName("s_3")
        self.b_1 = QtWidgets.QSlider(self.centralwidget)
        self.b_1.setGeometry(QtCore.QRect(10, 280, 160, 22))
        self.b_1.setOrientation(QtCore.Qt.Horizontal)
        self.b_1.setObjectName("b_1")
        self.b_3 = QtWidgets.QSlider(self.centralwidget)
        self.b_3.setGeometry(QtCore.QRect(10, 340, 160, 22))
        self.b_3.setOrientation(QtCore.Qt.Horizontal)
        self.b_3.setObjectName("b_3")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslate_ui(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apply_wind.setText(_translate("MainWindow", "Apply"))
        self.width.setText(_translate("MainWindow", "Width"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox.setItemText(9, _translate("MainWindow", "9"))
        self.apply_color.setText(_translate("MainWindow", "Apply"))
        self.color_box.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Setting the window size"))
        self.label_2.setText(_translate("MainWindow", "Setting the color of the squares"))
        self.apply_beck.setText(_translate("MainWindow", "Apply"))
        self.color_back_la.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Setting background color"))

